# Generated by Django 3.0.1 on 2020-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.TextField()),
                ("Email", models.TextField()),
                ("Phone", models.TextField()),
            ],
        ),
    ]
