# Generated by Django 3.0.1 on 2020-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="Education",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="Location",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="Publications",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="languages",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="references",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
