# Generated by Django 3.0.1 on 2020-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offers",
            name="company_mail",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
